version: '3'
services:

  postgres:
      container_name: postgres
      image: postgres:10.3-alpine
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: user
        POSTGRES_DB: test
      volumes:
        - ./postgres/data:/var/lib/postgresql/data